name: Post

on:
  schedule:
    - cron: '0 1 * * 1,2,3,4,5'
  workflow_dispatch:

jobs:
  astro-ph-GA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install astro-ph
      - name: Post articles to Slack
        run: |
          astro-ph slack \
            --categories astro-ph.GA \
            --lang_to ja \
            --webhook_url ${{ secrets.SLACK_WEBHOOK_GA }}
            --debug
  astro-ph-IM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install astro-ph
      - name: Post articles to Slack
        run: |
          astro-ph slack \
            --categories astro-ph.IM \
            --lang_to ja \
            --webhook_url ${{ secrets.SLACK_WEBHOOK_IM }}
            --debug
